swagger: "2.0"
info:
    title: Policy Service
    description: The policy service exposes HTTP API for executing policies.
    version: ""
host: localhost:8081
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /liveness:
        get:
            tags:
                - health
            summary: Liveness health
            operationId: health#Liveness
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HealthLivenessResponseBody'
                        required:
                            - service
                            - status
                            - version
            schemes:
                - http
    /policy/{repository}/{group}/{policyName}/{version}/evaluation:
        get:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate#1
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  type: string
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  required: false
                  type: string
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  required: false
                  type: integer
                - name: any
                  in: body
                  description: Input data passed to the policy execution runtime.
                  required: true
                  schema:
                    type: string
                    format: binary
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: binary
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            type: string
            schemes:
                - http
        post:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate#2
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  type: string
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  required: false
                  type: string
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  required: false
                  type: integer
                - name: any
                  in: body
                  description: Input data passed to the policy execution runtime.
                  required: true
                  schema:
                    type: string
                    format: binary
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: binary
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            type: string
            schemes:
                - http
    /policy/{repository}/{group}/{policyName}/{version}/evaluation/did.json:
        get:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  type: string
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  required: false
                  type: string
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  required: false
                  type: integer
                - name: any
                  in: body
                  description: Input data passed to the policy execution runtime.
                  required: true
                  schema:
                    type: string
                    format: binary
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: binary
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            type: string
            schemes:
                - http
    /policy/{repository}/{group}/{policyName}/{version}/export:
        get:
            tags:
                - policy
            summary: ExportBundle policy
            description: Export a signed policy bundle.
            operationId: policy#ExportBundle
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  type: string
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    headers:
                        content-disposition:
                            description: Content-Disposition response header containing the name of the file.
                            type: string
                        content-length:
                            description: Content-Length response header.
                            type: int
                        content-type:
                            description: Content-Type response header.
                            type: string
            schemes:
                - http
    /policy/{repository}/{group}/{policyName}/{version}/key:
        get:
            tags:
                - policy
            summary: PolicyPublicKey policy
            description: PolicyPublicKey returns the public key in JWK format which must be used to verify a signed policy bundle.
            operationId: policy#PolicyPublicKey
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  type: string
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: binary
            schemes:
                - http
    /policy/{repository}/{group}/{policyName}/{version}/lock:
        post:
            tags:
                - policy
            summary: Lock policy
            description: Lock a policy so that it cannot be evaluated.
            operationId: policy#Lock
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  type: string
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
        delete:
            tags:
                - policy
            summary: Unlock policy
            description: Unlock a policy so it can be evaluated again.
            operationId: policy#Unlock
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  type: string
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /policy/{repository}/{group}/{policyName}/{version}/notifychange:
        post:
            tags:
                - policy
            summary: SubscribeForPolicyChange policy
            description: Subscribe for policy change notifications by registering webhook callbacks which the policy service will call.
            operationId: policy#SubscribeForPolicyChange
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  type: string
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
                - name: SubscribeForPolicyChangeRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/PolicySubscribeForPolicyChangeRequestBody'
                    required:
                        - webhook_url
                        - subscriber
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: binary
            schemes:
                - http
    /policy/import:
        post:
            tags:
                - policy
            summary: ImportBundle policy
            description: Import a signed policy bundle.
            operationId: policy#ImportBundle
            parameters:
                - name: Content-Length
                  in: header
                  required: false
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: binary
                "403":
                    description: Forbidden response.
                    schema:
                        type: string
                        format: binary
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
                        format: binary
            schemes:
                - http
    /readiness:
        get:
            tags:
                - health
            summary: Readiness health
            operationId: health#Readiness
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HealthReadinessResponseBody'
                        required:
                            - service
                            - status
                            - version
            schemes:
                - http
    /v1/policies:
        get:
            tags:
                - policy
            summary: ListPolicies policy
            description: List policies from storage with optional filters.
            operationId: policy#ListPolicies
            parameters:
                - name: locked
                  in: query
                  description: Filter to return locked/unlocked policies (optional).
                  required: false
                  type: boolean
                - name: rego
                  in: query
                  description: Include policy source code in results (optional).
                  required: false
                  type: boolean
                - name: data
                  in: query
                  description: 'Include policy static data in results (optional). '
                  required: false
                  type: boolean
                - name: dataConfig
                  in: query
                  description: Include static data config (optional).
                  required: false
                  type: boolean
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PolicyListPoliciesResponseBody'
                        required:
                            - policies
            schemes:
                - http
definitions:
    HealthLivenessResponseBody:
        title: HealthLivenessResponseBody
        type: object
        properties:
            service:
                type: string
                description: Service name.
                example: Ut unde pariatur velit esse.
            status:
                type: string
                description: Status message.
                example: Veniam repudiandae delectus facere est.
            version:
                type: string
                description: Service runtime version.
                example: Commodi esse repellendus reiciendis molestias qui.
        example:
            service: Nostrum animi omnis.
            status: Nihil consectetur quibusdam.
            version: Voluptatum dolor provident dolorum nihil.
        required:
            - service
            - status
            - version
    HealthReadinessResponseBody:
        title: HealthReadinessResponseBody
        type: object
        properties:
            service:
                type: string
                description: Service name.
                example: Eius culpa velit est.
            status:
                type: string
                description: Status message.
                example: Et numquam non rerum.
            version:
                type: string
                description: Service runtime version.
                example: Quis eius voluptas est ipsum.
        example:
            service: Rerum exercitationem odit tempora ab in aliquid.
            status: Deleniti odit dolor et et.
            version: Libero sed a at.
        required:
            - service
            - status
            - version
    PolicyListPoliciesResponseBody:
        title: PolicyListPoliciesResponseBody
        type: object
        properties:
            policies:
                type: array
                items:
                    $ref: '#/definitions/PolicyResponseBody'
                description: JSON array of policies.
                example:
                    - data: Quae et et unde.
                      dataConfig: Dolore ducimus accusamus et voluptatibus cupiditate.
                      group: Ut est ut molestias sint ipsam.
                      lastUpdate: 4907765416681941118
                      locked: true
                      policyName: Architecto id.
                      rego: Aperiam aut odio dolorum.
                      repository: Architecto iure est.
                      version: At ut dolore.
                    - data: Quae et et unde.
                      dataConfig: Dolore ducimus accusamus et voluptatibus cupiditate.
                      group: Ut est ut molestias sint ipsam.
                      lastUpdate: 4907765416681941118
                      locked: true
                      policyName: Architecto id.
                      rego: Aperiam aut odio dolorum.
                      repository: Architecto iure est.
                      version: At ut dolore.
        example:
            policies:
                - data: Quae et et unde.
                  dataConfig: Dolore ducimus accusamus et voluptatibus cupiditate.
                  group: Ut est ut molestias sint ipsam.
                  lastUpdate: 4907765416681941118
                  locked: true
                  policyName: Architecto id.
                  rego: Aperiam aut odio dolorum.
                  repository: Architecto iure est.
                  version: At ut dolore.
                - data: Quae et et unde.
                  dataConfig: Dolore ducimus accusamus et voluptatibus cupiditate.
                  group: Ut est ut molestias sint ipsam.
                  lastUpdate: 4907765416681941118
                  locked: true
                  policyName: Architecto id.
                  rego: Aperiam aut odio dolorum.
                  repository: Architecto iure est.
                  version: At ut dolore.
        required:
            - policies
    PolicyResponseBody:
        title: PolicyResponseBody
        type: object
        properties:
            data:
                type: string
                description: Policy static data.
                example: Et exercitationem perspiciatis quidem accusamus.
            dataConfig:
                type: string
                description: Policy static data optional configuration.
                example: Molestiae fugiat harum quia corporis ullam natus.
            group:
                type: string
                description: Policy group.
                example: Dignissimos enim.
            lastUpdate:
                type: integer
                description: Last update (Unix timestamp).
                example: 1661279390509210298
                format: int64
            locked:
                type: boolean
                description: Locked specifies if the policy is locked or allowed to execute.
                example: true
            policyName:
                type: string
                description: Policy name.
                example: Cupiditate qui quo.
            rego:
                type: string
                description: Policy rego source code.
                example: Et sit qui fugit enim labore.
            repository:
                type: string
                description: Policy repository.
                example: Sed ea et ad omnis possimus.
            version:
                type: string
                description: Policy version.
                example: Error et sunt maxime aperiam.
        example:
            data: Facilis tempora dolor consectetur.
            dataConfig: Consequatur aut ipsam.
            group: Dolores laborum.
            lastUpdate: 3149592520373289900
            locked: true
            policyName: Et eius sed molestias rerum.
            rego: Vel eveniet voluptas rerum.
            repository: Minima fuga numquam sint ipsum explicabo assumenda.
            version: Voluptas eos nemo.
        required:
            - repository
            - group
            - policyName
            - version
            - locked
            - lastUpdate
    PolicySubscribeForPolicyChangeRequestBody:
        title: PolicySubscribeForPolicyChangeRequestBody
        type: object
        properties:
            subscriber:
                type: string
                description: Name of the subscriber for policy.
                example: aaf
                minLength: 3
                maxLength: 100
            webhook_url:
                type: string
                description: Subscriber webhook url.
                example: http://cartwright.biz/skyla
                format: uri
        example:
            subscriber: 1v2
            webhook_url: http://gutkowski.name/adrian.stroman
        required:
            - webhook_url
            - subscriber
