openapi: 3.0.3
info:
    title: Policy Service
    description: The policy service exposes HTTP API for executing policies.
    version: "1.0"
servers:
    - url: http://localhost:8081
      description: Policy Server
paths:
    /liveness:
        get:
            tags:
                - health
            summary: Liveness health
            operationId: health#Liveness
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HealthResponse'
                            example:
                                service: Rerum asperiores nulla.
                                status: Tenetur rerum necessitatibus fugit.
                                version: Ut velit aut nobis repellendus.
    /policy/{repository}/{group}/{policyName}/{version}/evaluation:
        get:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate#1
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  schema:
                    type: string
                    description: Policy repository.
                    example: policies
                  example: policies
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: example
                  example: example
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: example
                  example: example
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: "1.0"
                  example: "1.0"
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: EvaluationID allows overwriting the randomly generated evaluationID
                    example: did:web:example.com
                  example: did:web:example.com
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Policy result cache TTL in seconds
                    example: 60
                    format: int64
                  example: 60
            requestBody:
                description: Input data passed to the policy execution runtime.
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            description: Input data passed to the policy execution runtime.
                            example: Ut unde pariatur velit esse.
                            format: binary
                        example: Aspernatur sit est corrupti ullam commodi porro.
            responses:
                "200":
                    description: OK response.
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            required: true
                            schema:
                                type: string
                                description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                                example: Perferendis necessitatibus.
                            example: Id distinctio perspiciatis.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: Arbitrary JSON response.
                                example: Veniam repudiandae delectus facere est.
                                format: binary
                            example: Et in dolorem.
        post:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate#2
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  schema:
                    type: string
                    description: Policy repository.
                    example: policies
                  example: policies
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: example
                  example: example
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: example
                  example: example
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: "1.0"
                  example: "1.0"
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: EvaluationID allows overwriting the randomly generated evaluationID
                    example: did:web:example.com
                  example: did:web:example.com
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Policy result cache TTL in seconds
                    example: 60
                    format: int64
                  example: 60
            requestBody:
                description: Input data passed to the policy execution runtime.
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            description: Input data passed to the policy execution runtime.
                            example: Ut unde pariatur velit esse.
                            format: binary
                        example: Consequatur cupiditate aut consequuntur in animi.
            responses:
                "200":
                    description: OK response.
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            required: true
                            schema:
                                type: string
                                description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                                example: Aspernatur ut ab nam quis repellendus.
                            example: Blanditiis quia.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: Arbitrary JSON response.
                                example: Veniam repudiandae delectus facere est.
                                format: binary
                            example: Mollitia repellendus consequuntur.
    /policy/{repository}/{group}/{policyName}/{version}/evaluation/did.json:
        get:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  schema:
                    type: string
                    description: Policy repository.
                    example: policies
                  example: policies
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: example
                  example: example
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: example
                  example: example
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: "1.0"
                  example: "1.0"
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: EvaluationID allows overwriting the randomly generated evaluationID
                    example: did:web:example.com
                  example: did:web:example.com
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Policy result cache TTL in seconds
                    example: 60
                    format: int64
                  example: 60
            requestBody:
                description: Input data passed to the policy execution runtime.
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            description: Input data passed to the policy execution runtime.
                            example: Ut unde pariatur velit esse.
                            format: binary
                        example: Saepe ut.
            responses:
                "200":
                    description: OK response.
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            required: true
                            schema:
                                type: string
                                description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                                example: Et sit sint ratione.
                            example: Sequi culpa consequatur dolorum incidunt dolorum.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: Arbitrary JSON response.
                                example: Veniam repudiandae delectus facere est.
                                format: binary
                            example: Expedita ea non minus reiciendis.
    /policy/{repository}/{group}/{policyName}/{version}/lock:
        delete:
            tags:
                - policy
            summary: Unlock policy
            description: Unlock a policy so it can be evaluated again.
            operationId: policy#Unlock
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  schema:
                    type: string
                    description: Policy repository.
                    example: Illum iste repellat sequi libero.
                  example: Vitae praesentium ratione enim nihil sit explicabo.
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: Quia dolor rem eius molestias.
                  example: Libero voluptas.
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: Voluptas eum eaque sit eum similique est.
                  example: Praesentium rerum dignissimos aliquam cumque.
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: Reprehenderit est.
                  example: Esse est aspernatur quo adipisci numquam excepturi.
            responses:
                "200":
                    description: OK response.
        post:
            tags:
                - policy
            summary: Lock policy
            description: Lock a policy so that it cannot be evaluated.
            operationId: policy#Lock
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  schema:
                    type: string
                    description: Policy repository.
                    example: Eveniet excepturi repellendus similique in mollitia voluptas.
                  example: Neque est dolore.
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: Harum non id sint iusto quaerat.
                  example: Nisi illum nulla sit in.
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: Et eligendi molestiae.
                  example: Nulla eligendi labore.
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: Et non similique quo qui saepe.
                  example: Tempore vero illo deleniti quidem omnis vitae.
            responses:
                "200":
                    description: OK response.
    /policy/{repository}/{group}/{policyName}/{version}/notifychange:
        post:
            tags:
                - policy
            summary: SubscribeForPolicyChange policy
            description: Subscribe for policy change notifications by registering webhook callbacks which the policy service will call.
            operationId: policy#SubscribeForPolicyChange
            parameters:
                - name: repository
                  in: path
                  description: Policy repository.
                  required: true
                  schema:
                    type: string
                    description: Policy repository.
                    example: Unde incidunt.
                  example: In voluptas eius cupiditate ut ipsam ipsa.
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: Eveniet velit voluptatem eligendi doloremque tenetur.
                  example: Itaque non.
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: Sint quis.
                  example: Voluptas enim nulla.
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: Aut et saepe dolores.
                  example: Corporis quos recusandae et earum.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SubscribeForPolicyChangeRequestBody'
                        example:
                            subscriber: l5c
                            webhook_url: http://kilback.com/delbert
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Assumenda quis eaque voluptatem explicabo perspiciatis.
                                format: binary
                            example: Pariatur fugit non incidunt ut quidem.
    /readiness:
        get:
            tags:
                - health
            summary: Readiness health
            operationId: health#Readiness
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HealthResponse'
                            example:
                                service: Rem et occaecati quam.
                                status: Laborum harum voluptate et ut similique doloremque.
                                version: Explicabo expedita ipsum minus ipsam at vel.
    /v1/policies:
        get:
            tags:
                - policy
            summary: ListPolicies policy
            description: List policies from storage with optional filters.
            operationId: policy#ListPolicies
            parameters:
                - name: locked
                  in: query
                  description: Filter to return locked/unlocked policies (optional).
                  allowEmptyValue: true
                  schema:
                    type: boolean
                    description: Filter to return locked/unlocked policies (optional).
                    example: true
                  example: true
                - name: rego
                  in: query
                  description: Include policy source code in results (optional).
                  allowEmptyValue: true
                  schema:
                    type: boolean
                    description: Include policy source code in results (optional).
                    example: false
                  example: true
                - name: data
                  in: query
                  description: 'Include policy static data in results (optional). '
                  allowEmptyValue: true
                  schema:
                    type: boolean
                    description: 'Include policy static data in results (optional). '
                    example: false
                  example: true
                - name: dataConfig
                  in: query
                  description: Include static data config (optional).
                  allowEmptyValue: true
                  schema:
                    type: boolean
                    description: Include static data config (optional).
                    example: true
                  example: true
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PoliciesResult'
                            example:
                                policies:
                                    - data: Vel dolores omnis molestiae tempora sed repellendus.
                                      dataConfig: Error minus vel voluptate quasi.
                                      group: Rerum molestiae possimus cum laboriosam.
                                      lastUpdate: 4744199804826420990
                                      locked: true
                                      policyName: Qui nostrum eaque nesciunt et dolores et.
                                      rego: Aut asperiores.
                                      repository: Et minus fugiat veritatis.
                                      version: Ipsa ad voluptatum maxime ut.
                                    - data: Vel dolores omnis molestiae tempora sed repellendus.
                                      dataConfig: Error minus vel voluptate quasi.
                                      group: Rerum molestiae possimus cum laboriosam.
                                      lastUpdate: 4744199804826420990
                                      locked: true
                                      policyName: Qui nostrum eaque nesciunt et dolores et.
                                      rego: Aut asperiores.
                                      repository: Et minus fugiat veritatis.
                                      version: Ipsa ad voluptatum maxime ut.
                                    - data: Vel dolores omnis molestiae tempora sed repellendus.
                                      dataConfig: Error minus vel voluptate quasi.
                                      group: Rerum molestiae possimus cum laboriosam.
                                      lastUpdate: 4744199804826420990
                                      locked: true
                                      policyName: Qui nostrum eaque nesciunt et dolores et.
                                      rego: Aut asperiores.
                                      repository: Et minus fugiat veritatis.
                                      version: Ipsa ad voluptatum maxime ut.
components:
    schemas:
        HealthResponse:
            type: object
            properties:
                service:
                    type: string
                    description: Service name.
                    example: Autem exercitationem nobis voluptas perferendis nemo.
                status:
                    type: string
                    description: Status message.
                    example: Nemo voluptatem est dolorum eum atque.
                version:
                    type: string
                    description: Service runtime version.
                    example: Quae animi iusto alias quidem eaque.
            example:
                service: Ea nesciunt rerum laudantium rerum sequi.
                status: Odio vero.
                version: Expedita ipsa iste facere sint.
            required:
                - service
                - status
                - version
        PoliciesResult:
            type: object
            properties:
                policies:
                    type: array
                    items:
                        $ref: '#/components/schemas/Policy'
                    description: JSON array of policies.
                    example:
                        - data: Vel dolores omnis molestiae tempora sed repellendus.
                          dataConfig: Error minus vel voluptate quasi.
                          group: Rerum molestiae possimus cum laboriosam.
                          lastUpdate: 4744199804826420990
                          locked: true
                          policyName: Qui nostrum eaque nesciunt et dolores et.
                          rego: Aut asperiores.
                          repository: Et minus fugiat veritatis.
                          version: Ipsa ad voluptatum maxime ut.
                        - data: Vel dolores omnis molestiae tempora sed repellendus.
                          dataConfig: Error minus vel voluptate quasi.
                          group: Rerum molestiae possimus cum laboriosam.
                          lastUpdate: 4744199804826420990
                          locked: true
                          policyName: Qui nostrum eaque nesciunt et dolores et.
                          rego: Aut asperiores.
                          repository: Et minus fugiat veritatis.
                          version: Ipsa ad voluptatum maxime ut.
                        - data: Vel dolores omnis molestiae tempora sed repellendus.
                          dataConfig: Error minus vel voluptate quasi.
                          group: Rerum molestiae possimus cum laboriosam.
                          lastUpdate: 4744199804826420990
                          locked: true
                          policyName: Qui nostrum eaque nesciunt et dolores et.
                          rego: Aut asperiores.
                          repository: Et minus fugiat veritatis.
                          version: Ipsa ad voluptatum maxime ut.
                        - data: Vel dolores omnis molestiae tempora sed repellendus.
                          dataConfig: Error minus vel voluptate quasi.
                          group: Rerum molestiae possimus cum laboriosam.
                          lastUpdate: 4744199804826420990
                          locked: true
                          policyName: Qui nostrum eaque nesciunt et dolores et.
                          rego: Aut asperiores.
                          repository: Et minus fugiat veritatis.
                          version: Ipsa ad voluptatum maxime ut.
            example:
                policies:
                    - data: Vel dolores omnis molestiae tempora sed repellendus.
                      dataConfig: Error minus vel voluptate quasi.
                      group: Rerum molestiae possimus cum laboriosam.
                      lastUpdate: 4744199804826420990
                      locked: true
                      policyName: Qui nostrum eaque nesciunt et dolores et.
                      rego: Aut asperiores.
                      repository: Et minus fugiat veritatis.
                      version: Ipsa ad voluptatum maxime ut.
                    - data: Vel dolores omnis molestiae tempora sed repellendus.
                      dataConfig: Error minus vel voluptate quasi.
                      group: Rerum molestiae possimus cum laboriosam.
                      lastUpdate: 4744199804826420990
                      locked: true
                      policyName: Qui nostrum eaque nesciunt et dolores et.
                      rego: Aut asperiores.
                      repository: Et minus fugiat veritatis.
                      version: Ipsa ad voluptatum maxime ut.
                    - data: Vel dolores omnis molestiae tempora sed repellendus.
                      dataConfig: Error minus vel voluptate quasi.
                      group: Rerum molestiae possimus cum laboriosam.
                      lastUpdate: 4744199804826420990
                      locked: true
                      policyName: Qui nostrum eaque nesciunt et dolores et.
                      rego: Aut asperiores.
                      repository: Et minus fugiat veritatis.
                      version: Ipsa ad voluptatum maxime ut.
            required:
                - policies
        Policy:
            type: object
            properties:
                data:
                    type: string
                    description: Policy static data.
                    example: Et numquam non rerum.
                dataConfig:
                    type: string
                    description: Policy static data optional configuration.
                    example: Quis eius voluptas est ipsum.
                group:
                    type: string
                    description: Policy group.
                    example: Nihil consectetur quibusdam.
                lastUpdate:
                    type: integer
                    description: Last update (Unix timestamp).
                    example: 4510165010623668447
                    format: int64
                locked:
                    type: boolean
                    description: Locked specifies if the policy is locked or allowed to execute.
                    example: true
                policyName:
                    type: string
                    description: Policy name.
                    example: Nostrum animi omnis.
                rego:
                    type: string
                    description: Policy rego source code.
                    example: Eius culpa velit est.
                repository:
                    type: string
                    description: Policy repository.
                    example: Commodi esse repellendus reiciendis molestias qui.
                version:
                    type: string
                    description: Policy version.
                    example: Voluptatum dolor provident dolorum nihil.
            example:
                data: Qui et sit maiores architecto alias.
                dataConfig: Nesciunt labore voluptatibus.
                group: Et et qui libero.
                lastUpdate: 731402412785725769
                locked: false
                policyName: Aliquid omnis deleniti odit.
                rego: Delectus sint quia blanditiis.
                repository: Odit tempora ab.
                version: A at ipsum.
            required:
                - repository
                - group
                - policyName
                - version
                - locked
                - lastUpdate
        SubscribeForPolicyChangeRequestBody:
            type: object
            properties:
                subscriber:
                    type: string
                    description: Name of the subscriber for policy.
                    example: 9r5
                    minLength: 3
                    maxLength: 100
                webhook_url:
                    type: string
                    description: Subscriber webhook url.
                    example: http://dooleystamm.name/kurtis_champlin
                    format: uri
            example:
                subscriber: k7i
                webhook_url: http://corkery.org/lyda
            required:
                - webhook_url
                - subscriber
tags:
    - name: policy
      description: Policy Service provides evaluation of policies through Open Policy Agent.
    - name: health
      description: Health service provides health check endpoints.
